from .src.SAM3Segmentation import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .src.sam3_interactive import NODE_CLASS_MAPPINGS as INTERACTIVE_MAPPINGS
from .src.sam3_interactive import NODE_DISPLAY_NAME_MAPPINGS as INTERACTIVE_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS.update(NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(INTERACTIVE_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS.update(NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(INTERACTIVE_DISPLAY_MAPPINGS)

WEB_DIRECTORY = "./web"
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
